tracker/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :goals
  
  root 'welcome#index'

  get "/login" => "sessions#new"
  resource  :session, only: [:create, :destroy]
  

end

tracker/app/models/appointment.rb
class Appointment < ActiveRecord::Base
end

tracker/app/models/goal.rb
class Goal < ActiveRecord::Base
	validates :habits, presence: true
	validates_length_of :habits_desc, :minimum => 10, :maximum => 300
	belongs_to :user

end

tracker/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	validates :password_confirmation, presence: true
	validates :email, presence: true, uniqueness: {message: "This email has already been used to login"}
	has_many :goals
end

tracker/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authenticate
    unless current_user
      redirect_to login_path
    end
  end
end

tracker/app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal, only: [:show, :edit, :update, :destroy]

  # GET /habits
  # GET /habits.json
  def index
    @goals = Goal.all
  end

  # GET /habits/1
  # GET /habits/1.json
  def show
  	@goal = Goal.find(params[:id])
  end

  # GET /habits/new
  def new
    @goal = Goal.new
  end

  # GET /habits/1/edit
  def edit
  end

  # POST /habits
  # POST /habits.json
  def create
    @goal = Goal.new(goal_params)
    respond_to do |format|
      if @goal.save
        format.html { redirect_to goals_url, notice: 'Goal was successfully created.' }
        format.json { render :show, status: :created, location: @goal }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /habits/1
  # PATCH/PUT /habits/1.json
  def update
    respond_to do |format|
      if @goal.update(goal_params)
        format.html { redirect_to @goal, notice: 'Goal was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal }
      else
        format.html { render :edit }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /habits/1
  # DELETE /habits/1.json
  def destroy
    @goal.destroy
    respond_to do |format|
      format.html { redirect_to @goal, notice: 'Goal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_goal
      @goal = Goal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def goal_params
      params.require(:goal).permit(:user_id, :habits, :habits_desc, :days_completed, :days_missed)
    end
end

tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end


  def create
  	debugger
      @user = User.find_by(name: params[:username])
      if @user && @user.authenticate(params[:password])
          session[:user_id] = @user.id
          redirect_to(user_path(@user))
      else
          flash[:error] = "Incorrect Username or Password"
          redirect_to(login_path)
      end
  end

  def destroy
    reset_session
    redirect_to(login_path)
  end

end

tracker/app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate, except: [:new, :create]

def show
  @user = User.find(params[:id])
end

def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render template: "sessions/new"
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end
end

tracker/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	  if session[:user_id]
	    user = User.find_by(id: session[:user_id])
	    redirect_to user_path(id: session[:user_id])
	  else
	  	redirect_to(login_path)
	  end
	end
end

tracker/app/helpers/application_helper.rb
module ApplicationHelper
end

tracker/app/views/goals/_form.html.erb
<div class="pure-form">
  <%= form_for(@goal) do |f| %>
    <% if @goal.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@goal.errors.count, "error") %> prohibited this habit from being saved:</h2>

        <ul>
        <% @goal.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
<form class="pure-form">
 <fieldset class="pure-group">
    <div class="pure-input-1-2">
      <%= f.label :habits %><br>
      <%= f.text_area :habits %>
    </div>
    <div class="pure-input-1-2">
      <%= f.label :habits_desc %><br>
      <%= f.text_area :habits_desc %>
    </div>
    <% f.hidden_field :days_completed, :value => "0" %>
    <% f.hidden_field :user_id, :value => user.id %>
    <% f.hidden_field :days_missed, :value => "0" %>
    <div class="pure-input-1-2">
      <%= f.submit %>
    </div>
  </fieldset>
  <% end %>
</div>
</form>

tracker/app/views/goals/edit.html.erb
<h1>edit goal:</h1>
<%= render 'form' %>

tracker/app/views/goals/index.html.erb
<p id="notice"><%= notice %></p>
  <%= link_to 'New Goal', new_goal_path %>
  <div id="goals"></div>
                      <% @goals.each do |goal| %>
<div class="pricing-tables pure-g">
        <div class="pure-u-1 pure-u-md-1-3">
            <div class="pricing-table pricing-table-free">
                <div class="pricing-table-header">
                    <h2><%= goal.habits %></h2>
                </div>
                <ul class="pricing-table-list">
                  <li><%= goal.habits_desc %></li>
                  <li><%= goal.days_completed %></li>
                </ul>
                <button class="button-choose pure-button"><%= link_to 'Edit', edit_goal_path(goal) %></button>
                <button class="button-choose pure-button"><%= link_to 'Destroy', goal, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            </div>
        </div>
      </div>
</div>
        <% end %>
  </body>
  </html>

tracker/app/views/goals/new.html.erb
<h1>Add new Goal</h1>
<%= render 'form' %>
<%= link_to 'Back', goals_path %>

tracker/app/views/goals/show.html.erb
<div class="pricing-table-header">
    <h2><%= @goal.habits %></h2>
</div>
<ul class="pricing-table-list">
  <li><%= @goal.habits_desc %></li>
  <li><%= @goal.days_completed %></li>
</ul>
<button class="button-choose pure-button"><%= link_to 'Edit', edit_goal_path(@goal) %></button>
<button class="button-choose pure-button"><%= link_to 'Destroy', @goal, method: :delete, data: { confirm: 'Are you sure?' } %></button>
</div>

tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'defaults', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Google Login -->
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <!-- Load jquery -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <!--   Pure css -->
  <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- stylesheet -->
  <link rel="stylesheet" type="text/css" href="./styles.css.scss">

</head>
<body>
  <div class="pure-menu pure-menu-horizontal">
    <a href="/goals" class="pure-menu-heading pure-menu-link">successCue</a>
    <ul class="pure-menu-list">
        <li class="pure-menu-item"><a href="/goals" class="pure-menu-link">Dashboard</a></li>
        <li class="pure-menu-item"><a href="/goals" class="pure-menu-link">Home</a></li>
        <li class="pure-menu-item"><a href="#" class="pure-menu-link">Help</a></li>
    </ul>
</div>
	<%= yield %>
</body>
</html>

tracker/app/views/users/show.html.erb
Hello <%= @user.name %>
<%= link_to 'Back', goals_path %>

tracker/app/views/welcome/index.html.erb
<h1>3</h1>